// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6e669cea-b26f-4351-8e2b-6b4def633315";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTemperaturaNuvemChange();
void onUmidadeSoloNuvem10Change();
void onUmidadeSoloNuvem14Change();
void onUmidadeSoloNuvem3Change();
void onLuminosidadeNuvemChange();
void onUmidadeNuvemChange();
void onLedTesteChange();
void onReleAChange();
void onReleBChange();

CloudTemperatureSensor temperaturaNuvem;
int umidadeSoloNuvem_10;
int umidadeSoloNuvem_14;
int umidadeSoloNuvem_3;
CloudLuminousIntensity luminosidadeNuvem;
CloudRelativeHumidity umidadeNuvem;
bool led_teste;
bool releA;
bool releB;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperaturaNuvem, READWRITE, ON_CHANGE, onTemperaturaNuvemChange);
  ArduinoCloud.addProperty(umidadeSoloNuvem_10, READWRITE, ON_CHANGE, onUmidadeSoloNuvem10Change);
  ArduinoCloud.addProperty(umidadeSoloNuvem_14, READWRITE, ON_CHANGE, onUmidadeSoloNuvem14Change);
  ArduinoCloud.addProperty(umidadeSoloNuvem_3, READWRITE, ON_CHANGE, onUmidadeSoloNuvem3Change);
  ArduinoCloud.addProperty(luminosidadeNuvem, READWRITE, ON_CHANGE, onLuminosidadeNuvemChange);
  ArduinoCloud.addProperty(umidadeNuvem, READWRITE, ON_CHANGE, onUmidadeNuvemChange);
  ArduinoCloud.addProperty(led_teste, READWRITE, ON_CHANGE, onLedTesteChange);
  ArduinoCloud.addProperty(releA, READWRITE, ON_CHANGE, onReleAChange);
  ArduinoCloud.addProperty(releB, READWRITE, ON_CHANGE, onReleBChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
